const greetings = [
    "Hello World!",
    "Hello Wêreld!",
    "Përshendetje Botë!",
    "ሰላም ልዑል!",
    "Բարեւ աշխարհ!",
    "Kaixo Mundua!",
    "Прывітанне Сусвет!",
    "ওহে বিশ্ব!",
    "Здравей свят!",
    "Hola món!",
    "Moni Dziko Lapansi!",
    "你好世界！",
    "Pozdrav svijete!",
    "Ahoj světe!",
    "Hej Verden!",
    "Hallo Wereld!",
    "Hello World!",
    "Tere maailm!",
    "Hei maailma!",
    "Bonjour monde!",
    "Hallo wrâld!",
    "გამარჯობა მსოფლიო!",
    "Hallo Welt!",
    "Γειά σου Κόσμε!",
    "Sannu Duniya!",
    "नमस्ते दुनिया!",
    "Helló Világ!",
    "Halló heimur!",
    "Ndewo Ụwa!",
    "Halo Dunia!",
    "Ciao mondo!",
    "こんにちは世界！",
    "Сәлем Әлем!",
    "Салам дүйнө!",
    "Sveika pasaule!",
    "Labas pasauli!",
    "Moien Welt!",
    "Здраво свету!",
    "Hai dunia!",
    "ഹലോ വേൾഡ്!",
    "Сайн уу дэлхий!",
    "မင်္ဂလာပါကမ္ဘာလောက!",
    "नमस्कार संसार!",
    "Hei Verden!",
    "Witaj świecie!",
    "Olá Mundo!",
    "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
    "Salut Lume!",
    "Привет мир!",
    "aelic: 	Hàlo a Shaoghail!",
    "Здраво Свете!",
    "Lefatše Lumela!",
    "හෙලෝ වර්ල්ඩ්!",
    "Pozdravljen svet!",
    "¡Hola Mundo!",
    "Halo Dunya!",
    "Salamu Dunia!",
    "Hej världen!",
    "Салом Ҷаҳон!",
    "สวัสดีชาวโลก!",
    "Selam Dünya!",
    "Привіт Світ!",
    "Salom Dunyo!",
    "Chào thế giới!",
    "Helo Byd!",
    "Molo Lizwe!",
    "העלא וועלט!",
    "Mo ki O Ile Aiye!",
    "Sawubona Mhlaba!"
]
export default greetings
